name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      postgres:
        image: postgres:16.1-alpine
        env:
          POSTGRES_USER: turing
          POSTGRES_PASSWORD: turing
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check server
        run: npm run type-check -w=server

      - name: Type check client
        run: npm run type-check -w=client

      - name: Lint server code
        run: npm run lint -w=server

      - name: Lint client code
        run: npm run lint -w=client

      # - name: Client tests
      #   run: npm run test:unit -w=client

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium firefox

      - name: Start server for E2E tests
        run: npm run start -w=server &
        env:
          DB_USER: turing
          DB_PASSWORD: turing
          DB_NAME: testdb

          PORT: 3000

      - name: Build front end for E2E tests
        run: npm run build -w=client
        env:
          VITE_API_ORIGIN: http://localhost:3000
          VITE_API_PATH: /api/v1/trpc

      - name: Health check
        uses: jtalk/url-health-check-action@v4
        with:
          # Check the following URLs one by one sequentially
          url: http://localhost:3000/api/health
          # Follow redirects, or just report success on 3xx status codes
          follow-redirect: false # Optional, defaults to "false"
          # Fail this action after this many failed attempts
          max-attempts: 5 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 5s # Optional, only applicable to max-attempts > 1

      - name: Test client E2E
        run: npm run test:e2e -w=client
